# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3d51499a12175fd3552a96ab53202c535a6baab1044026f310f7d573d548494af7fb9850b19b7122e54811b838967e4dec28c344d8ae74430f00141875770d6

test:
  secret_key_base: fabe5cea16d2d988bbde7565f17c135883b52afaee0449dce8a4ea3a269eb1dd54e1d76d08c8b82128ea1ea1c1725f1a21fb0504b81a42ffa09d299f3f8aadb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
