# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44976095ff8b88dbd90a0e8c95c167f11783b292831766b42934003d9e79b2376292d6105cb9165bc493ccf0835d43ef139e306ffb249723b2b7a712266312e5

test:
  secret_key_base: 412b74b13603047539a7edbba83c150b057d56d204894ada502ee771c5f14aa3f89e63150a03ef6d3ecddba0e7283bb496962bd859094dac124f12267c0dedc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
