# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60865287e0c64baf5ae726170909c6acafe8658e5d318b005812e4f71efbe6c5d883d166f094e5c5f24ef164886d41cc4b1b9c744d62de1ebdbf8aafadc70e9e

test:
  secret_key_base: 4be8a9592292b70debca315c955aa04b8993e90f4254f53831c1d0232b7ba0a648e25b027ce21778a2d314c040f1ee14ea95572b9548dccb755d6a6a15c2e99a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
