# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5f39806315f98807082ba2daedb9c1c0a1170ae8022e8772246cbae244b2231560e45e42ee0ee499bfb44f0b2913ed816dfff6980048d7a651d835b3d8febd6

test:
  secret_key_base: 0a3d675bdd5a3379f7b53ba95f8cba74294363aa2ffd21f8e4ef5bb79663a41f9b18e7f0ed020377003031e0d3c7c14624cf2440430a69fafe4cb9674890957b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
